dependencies {
    implementation('com.github.GTNewHorizons:GTNHLib:0.8.6:dev')
    implementation(rfg.deobf("curse.maven:muya1-7-10-530214:4364097"))
    implementation(rfg.deobf("curse.maven:manametal-531708:8569360"))
    implementation("com.github.GTNewHorizons:CodeChickenCore:1.4.7:dev")
    implementation("com.github.GTNewHorizons:NotEnoughItems:2.8.44-GTNH:dev")
    implementation(rfg.deobf("curse.maven:smooth-285742:2614474"))
    implementation(rfg.deobf("curse.maven:forge-nbtedit-for-1-7-10-381388:2949679"))
}
